In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    "A": [1, 2 , np.nan,4],
    "B": [ 5.1, np.nan,6.6,8.8],
    "C": ["foo","zoo","bar", np.nan],
    'D':[6,7,8,9]
})
print(df)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  NaN  zoo  7
2  NaN  6.6  bar  8
3  4.0  8.8  NaN  9

In [5]:
df.dropna(axis=1)

   D
0  6
1  7
2  8
3  9

In [8]:
df.fillna(0)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  0.0  zoo  7
2  0.0  6.6  bar  8
3  4.0  8.8    0  9

In [11]:
df.ffill(axis=0)

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  5.1  zoo  7
2  2.0  6.6  bar  8
3  4.0  8.8  bar  9

In [12]:
df.bfill()

     A    B    C  D
0  1.0  5.1  foo  6
1  2.0  6.6  zoo  7
2  4.0  6.6  bar  8
3  4.0  8.8  NaN  9