In [11]:
import pandas as pd
df=pd.read_csv('sp500.csv')
df

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30    NaN
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [4]:
df['Name'].str.lower()

0                       apple inc
1                      abbvie inc
2             abbott laboratories
3                   accenture plc
4                    allergan plc
                  ...
97     verizon communications inc
98       walgreens boots alliance
99          wells fargo & company
100               wal-mart stores
101              exxon mobil corp
Name: Name, Length: 102, dtype: str

In [12]:
l1=[]
for name in df['Name']:
    l1.append(name.lower())

df['Name']=l1

In [13]:
df

                           Name                  Sector   Price    EPS
0                     apple inc  Information Technology  170.12   9.20
1                    abbvie inc             Health Care   93.29   5.31
2           abbott laboratories             Health Care   55.28   2.41
3                 accenture plc  Information Technology  145.30    NaN
4                  allergan plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   verizon communications inc      Telecommunications   45.85   3.75
98     walgreens boots alliance        Consumer Staples   70.25   5.10
99        wells fargo & company              Financials   54.02   4.14
100             wal-mart stores        Consumer Staples   96.08   4.36
101            exxon mobil corp                  Energy   80.31   3.56

[102 rows x 4 columns]